version: "3.6"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=root:root@tcp(mysql:3306)/task_db?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    entrypoint: ["/app/start.sh"]
    command: [ "/app/task" ]

volumes:
  db_data: {}